### PR TITLE
PEP 622: Update motivation

### PR DESCRIPTION
**Pull request by dmoisset**
This is a WIP, but I'm rewriting the abstract and motivation sections as discussed in gvanrossum/patma#113 . 

I still may want to reorganize some of the info outside these sections, add more explanatory material, and perhaps include an additional examples section so there's still a lot to do here

### CODE REVIEW

**Comment by gvanrossum** [comment]
Why does this contain commits to other peps?

**Comment by dmoisset** [comment]
based on and old point of a branch that was updated. Let me rebase

**Comment by dmoisset** [comment]
Now it should be ok

**Comment by dmoisset** [comment]
Outdated

**Pull request closed without merging**
